### ISSUE TITLE
Feature Request: Auto Expand a filtered list

### ISSUE THREAD

**Issue by gw-bcharboneau** [axeleroy/aws-sso-auto-expand-accounts#1]
if i try to filter our list of AWS Accounts the Auto expand feature does not work. is it possible to add this as an option as we have many accounts.

**Comment by axeleroy** [comment]
Hello!

I did not know before today there was a way to filter accounts and indeed expanding does not work in this case. I'll look into it once I have some free time available.

**Comment by gw-bcharboneau** [comment]
Much appreciated!

**Comment by axeleroy** [comment]
Hi,

I just pushed an updated version that works in the filtered view. It's already available on Firefox's Add-ons, the Chrome Web Store ~should validate the version in the coming days~ version is now live.

**Comment by gw-bcharboneau** [comment]
Excellent, Works Great!
